### ISSUE TITLE
StationID now called ClimateID?

### ISSUE THREAD

**Issue by BastienFR** [gavinsimpson/canadaHCD#28]
Following the changes on EC side, it seems they are not using the `StationID` field as much now.  When you download a file directly (ex: [click on download)](https://climate.weather.gc.ca/climate_data/daily_data_e.html?hlyRange=%7C&dlyRange=1963-01-01%7C2019-08-31&mlyRange=1963-01-01%7C2018-02-01&StationID=5392&Prov=QC&urlExtension=_e.html&searchType=stnName&optLimit=yearRange&StartYear=1840&EndYear=2019&selRowPerPage=25&Line=0&searchMethod=contains&Month=8&Day=3&txtStationName=laurierville&timeframe=2&Year=2019), the file you get has no `StationID` field but only a `ClimateID` field.  This links to the `ClimateID` field in their table `Station Inventory EN.csv`.  In your `read_hcd` function, at line 48-56-63 the field name is hardcoded which in that case replace the original name and can cause confusion.

**Comment by gavinsimpson** [comment]
Thanks @BastienFR; yeah, I hadn't remembered these were two different things. I'll fix this.

**Comment by gavinsimpson** [comment]
I have changed `find_station()` to return `ClimateID` as well as `StationID`.

I should modify the other functions to allow a `ClimateID` to be used instead of the `StationID`. Perhaps along the lines of

```r
station_id(climate_id = 2204200) |> # ClimateID for YELLOWKNIFE HYDRO
  hcd_monthly()
```

where `station_id()` queries the station data table and returns the `StationID` for a given `ClimateID`. I could also add `climate_id(station_id)` for the reverse.

Internally, it still seems the URLs for the download system use the `StationID` info, so I still need to use those, but some helpers to facilitate going between the two would help?

**Comment by gavinsimpson** [comment]
`station_id()` and `climate_id()` are now implemented, I've modified `find_station()` to return the `ClimateID` also, and the data downloaded now use the right name `ClimateID`. So I'll call this one closed unless I've missed anything?

Thanks for the reports @BastienFR and sorry for the long delay in getting round to addressing them.
